# Generated by Django 3.2.25 on 2025-06-23 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_doubt'),
    ]

    operations = [
        migrations.AddField(
            model_name='doubt',
            name='reply',
            field=models.TextField(blank=True, null=True),
        ),
    ]
