# Generated by Django 3.2.25 on 2025-06-28 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_studentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='doubt',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_doubts', to='auth.user'),
            preserve_default=False,
        ),
    ]
