# Generated by Django 3.2.25 on 2025-06-29 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_poll_expires_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='Option',
        ),
        migrations.DeleteModel(
            name='Poll',
        ),
    ]
