# Generated by Django 3.2.25 on 2025-07-04 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_questionattempt_quizattempt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizattempt',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='quizattempt',
            name='student',
        ),
        migrations.DeleteModel(
            name='QuestionAttempt',
        ),
        migrations.DeleteModel(
            name='QuizAttempt',
        ),
    ]
