# Generated by Django 3.2.25 on 2025-07-06 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20250706_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='dark_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='dark_mode',
            field=models.BooleanField(default=False),
        ),
    ]
