# Generated by Django 3.2.25 on 2025-07-06 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20250706_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livequizquestion',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='polloption',
            name='poll',
        ),
        migrations.RemoveField(
            model_name='pollvote',
            name='poll',
        ),
        migrations.RemoveField(
            model_name='pollvote',
            name='selected_option',
        ),
        migrations.RemoveField(
            model_name='pollvote',
            name='user',
        ),
        migrations.RemoveField(
            model_name='studentquizresponse',
            name='question',
        ),
        migrations.RemoveField(
            model_name='studentquizresponse',
            name='student',
        ),
        migrations.DeleteModel(
            name='LiveQuizPoll',
        ),
        migrations.DeleteModel(
            name='LiveQuizQuestion',
        ),
        migrations.DeleteModel(
            name='Poll',
        ),
        migrations.DeleteModel(
            name='PollOption',
        ),
        migrations.DeleteModel(
            name='PollVote',
        ),
        migrations.DeleteModel(
            name='StudentQuizResponse',
        ),
    ]
